language: python
os:
- linux
- osx
dist: trusty
python:
  - "3.8"
  - "3.6"
jobs:
  include:
    - python: '3.8'
      env: EXTRA_TESTS=true
    - python: '3.6'
      env: EXTRA_TESTS=true

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
